--- # Disable Automounting
- name: Disable autofs
  shell: systemctl --now disable autofs
  ignore_errors: yes
  tags: autofs

- name: Remove autofs
  apt:
    name: autofs
    state: absent
  tags: autofs
