--- # Ensure TCP SYN Cookies is enabled
- name: Ensure TCP SYN Cookies is enabled - hardening.conf
  lineinfile:
    path: /etc/sysctl.d/hardening.conf
    line: 'net.ipv4.tcp_syncookies = 1'
  tags: tcp-syn-cookies

- name: Ensure TCP SYN Cookies is enabled - sysctl
  shell: sysctl -w net.ipv4.tcp_syncookies=1
  tags: tcp-syn-cookies
