--- # Ensure broadcast ICMP requests are ignored
- name: Ensure broadcast ICMP requests are ignored - hardening.conf
  lineinfile:
    path: /etc/sysctl.d/hardening.conf
    line: 'net.ipv4.icmp_echo_ignore_broadcasts = 1'
  tags: icmp-request

- name: Ensure broadcast ICMP requests are ignored - sysctl
  shell: sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1
  tags: icmp-request
