--- #Ensure suspicious packets are logged
- name: Ensure suspicious packets are logged - hardening.conf
  lineinfile:
    path: /etc/sysctl.d/hardening.conf
    line: "{{ item.line }}"
  loop:
    - { line: 'net.ipv4.conf.all.log_martians = 1' }
    - { line: 'net.ipv4.conf.default.log_martians = 1' }
  tags: suspicious-packets

- name: Ensure suspicious packets are logged - sysctl
  shell: sysctl -w net.ipv4.conf.all.log_martians=1
  tags: suspicious-packets

- name: Ensure suspicious packets are logged - sysctl
  shell: sysctl -w net.ipv4.conf.default.log_martians=1
  tags: suspicious-packets
