--- # Ensure permissions on /etc/crontab are configured 
- name: Configure permission cron files
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0700'
  loop:
    - { path: '/etc/crontab' }
    - { path: '/etc/cron.hourly' }
    - { path: '/etc/cron.daily' }
    - { path: '/etc/cron.weekly' }
    - { path: '/etc/cron.monthly' }
    - { path: '/etc/cron.d' }
  tags: permission-cron-files
