--- # Ensure permissions on /etc/ssh/sshd_config are configured
- name: Configure permission sshd_config
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  tags: sshd-permission
