--- # Ensure lockout for failed password attempts is configured
- name: Adjust common auth configuration
  lineinfile:
    path: /etc/pam.d/common-auth
    line: "{{ item.line }}"
  loop:
    - { line: 'auth     required       pam_tally.so deny=5 onerr=fail per_user unlock_time=900' }
    
- name: Adjust common acount configuration
  lineinfile:
    path: /etc/pam.d/common-account
    line: "{{ item.line }}"
  loop:
    - { line: 'account required pam_tally.so' }
  tags: common-account
