--- # Ensure default user shell timeout is 900 seconds or less
- name: Set TMOUT parameters profile
  lineinfile:
    path: /etc/profile
    line: 'readonly TMOUT=900 ; export TMOUT'
  tags:
    - tmout-bashrc
