--- # Ensure permissions on /etc/group- are configured
- name: Set permission chown group-
  file:
    path: /etc/group-
    owner: root
    group: root
    mode: '0600'
  tags:
    - permission-group-
